name: Deploy  React App
on: push
jobs:
  test_my_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
